apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cooktheryan-poi-map-app-dev
  annotations:
    argocd/app-name: cooktheryan-poi-map-app-dev
    backstage.io/kubernetes-id: cooktheryan-poi-map-app-dev
    backstage.io/kubernetes-namespace: cooktheryan
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=cooktheryan-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23JanusN/cooktheryan-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/cooktheryan/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/k8s/ns/cooktheryan/deployments/poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23bis.17gd.p1.openshiftapps.com/#https://github.com/Summit23JanusN/cooktheryan-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://poi-map-app-cooktheryan.apps.summit23bis.17gd.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:cooktheryan"
  system: workshop-system-cooktheryan
  consumesApis:
    - gateway-api-cooktheryan
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-cooktheryan
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:cooktheryan"
